In [129]:
import numpy as np
Ai=np.array([0.001963075,0.028716115,0.079749333])
kij=np.array([[0,0.2,0.3],[0.2,0,0.4],[0.3,0.4,0]])
compositions=np.array([0.25,0.25,0.5])
shape=kij.shape
alfa=np.array([0.039446,0.215632,0.482204])

In [130]:
np.sqrt(A*A)*(1-kij)

array([[0.03197346, 0.02557876, 0.02238142],
       [0.02557876, 0.03197346, 0.01918407],
       [0.02238142, 0.01918407, 0.03197346]])

In [131]:
Aij=np.array([np.sqrt(Ai[i]*Ai[j])*(1-kij[i,j]) for i in range(0,len(Ai)) for j in range(0,len(Ai))]).reshape(shape)
Aij

array([[0.00196307, 0.0060065 , 0.00875851],
       [0.0060065 , 0.02871612, 0.02871294],
       [0.00875851, 0.02871294, 0.07974933]])

In [132]:
A = np.sum([np.sum(compositions[i]*compositions[j]*Aij[i,j]) for i in range(0,len(Ai)) for j in range(0,len(Ai))])
A

0.03197345550398059

In [150]:
def alfa_fun(t,tc,acentric):
    m=0.37464+1.54226*acentric-0.26992*acentric**2
    reduced_temperature=t/tc
    return (1+m*(1-np.sqrt(reduced_temperature)))**2
from scipy.misc import derivative
T=298
tc=np.array([126.2,304.21,373.53])
acentric=np.array([0.0377,0.2236,0.0942])

In [133]:
A_i = np.array([(compositions[j]*Aij[:,j]) for j in range(0,len(Ai))])
A_i =np.array([2* np.sum(A_i[:,i]) for i in range(0,len(Ai))])
A_i

array([0.01274329, 0.04607424, 0.09848505])

In [152]:
A_derivate=np.sum([0.5*np.sum(compositions[i]*compositions[j]*Aij[i,j]*((T/alfa[i])*derivative(alfa_fun,T,args=(tc[i],acentric[i]))+(T/alfa[j])*derivative(alfa_fun,T,args=(tc[j],acentric[j])))) for i in range(0,len(Ai)) for j in range(0,len(Ai))])

696 µs ± 24.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [153]:
A_derivate

-0.0643107583690761