In [1]:
import numpy as np
from thermodynamics.mix.general.equilibrium import solve_eos, bubble_temperature,bubble_pressure, dew_pressure, dew_temperature
t=350
p=13.253461386909118

tc = np.array([513.92,407.85,507.6])
pc=np.array([61.48,36.4,30.25])
acentric=np.array([0.649,0.186,0.297])
kij=np.array([[0,0.2,0.3],[0.2,0,0.4],[0.3,0.4,0]])
liq_compositions=np.array([0.25,0.25,0.5])
vap_compositions=np.array([0.25,0.25,0.5])
shape=kij.shape

#A_liq,B_liq,A_i_liq,Aij_liq,dAdT_liq

In [2]:

solve_eos(t,p,tc,pc,acentric,liq_compositions,vap_compositions,kij,method='pr',alfa_function='mathias',mixing_rule='van_der_waals',diagram=False,properties=False,heat_capacity=None)

(array([0.37952987, 2.90322199, 0.14573689]),
 array([0.37952987, 2.90322199, 0.14573689]))

In [3]:
t=350
p=10
bubble_pressure(t,p,tc,pc,acentric,liq_compositions,vap_compositions,kij,method='pr',alfa_function='mathias',mixing_rule='van_der_waals')

(350,
 16.10732877448054,
 array([0.25, 0.25, 0.5 ]),
 array([0.10763587, 0.81045785, 0.08190628]))

In [4]:
t=350
p=10
bubble_temperature(t,p,tc,pc,acentric,liq_compositions,vap_compositions,kij,method='pr',alfa_function='mathias',mixing_rule='van_der_waals')

(320.6648363529506,
 10,
 array([0.25, 0.25, 0.5 ]),
 array([0.06223563, 0.89014601, 0.04761836]))

In [5]:
t=350
p=10
dew_pressure(t,p,tc,pc,acentric,liq_compositions,vap_compositions,kij,method='pr',alfa_function='mathias',mixing_rule='van_der_waals')

(350,
 2.1075112710078248,
 array([0.02803598, 0.00250251, 0.96946151]),
 array([0.25, 0.25, 0.5 ]))

In [6]:
t=350
p=10
dew_temperature(t,p,tc,pc,acentric,liq_compositions,vap_compositions,kij,method='pr',alfa_function='mathias',mixing_rule='van_der_waals')

(405.5006579421661,
 10,
 array([0.06078743, 0.01356209, 0.92565048]),
 array([0.25, 0.25, 0.5 ]))